todolist/config/routes.rb
Rails.application.routes.draw do

  get 'notebooks/index'

  get 'notebooks/new'

  get 'notebooks/update'

  get 'notebooks/delete'

  devise_for :users, controllers: {
          sessions: 'users/sessions',
          passwords: 'users/passwords',
          registrations: 'users/registrations'
  }


  resources :notebooks
  resources :tasks
  get 'notebooks/addtask'
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

todolist/app/models/notebook.rb
class Notebook < ApplicationRecord
  has_many :notebooktasks, class_name: "NotebookTask"
  has_many :tasks, through: :notebooktasks
  belongs_to :user, class_name: "User", foreign_key: "user_id"

    validates :name , presence: true
end

todolist/app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
    before_action :authenticate_user!
    def index
      @notebooks = Notebook.all
    end

    def new
      @notebooks = Notebook.new
    end

    def edit
      find_notebook
      if @notebooks.nil?
        flash[:error] = "Houston we are in troubles, please dont hack us."
        redirect_to root_path
      end
    end

    def create
      @notebooks = Notebook.new(notebook_params)
      @notebooks.user = current_user
      if @notebooks.save
        redirect_to notebooks_path
        flash[:success] = "Notebook created. Ok"
      else
        render 'new'
      end
    end

    def destroy
      find_notebook
      if @notebooks.destroy
        flash[:success] = "Notebook Destroyed Successfully"
      else
        flash[:error] = "Houston we are in troubles, please try it later"
      end
      redirect_to notebooks_path
    end

    def update
      find_notebook
      if @notebooks.update(notebook_params)
        flash[:success] = "Notebooks updated. Ok"
        redirect_to notebooks_path
      else
        flash[:error] = "Houston we are in troubles, try it again."
        render 'edit'
      end
    end


  def show
   find_notebook
   if @notebooks.nil?
     flash[:error] = "Houston we are in troubles, please dont hack us."
     redirect_to root_path
   end

   def addtask
     find_notebook
     if @notebooks.nil?
       flash[:error] = "Houston we are in troubles, please dont hack us."
       redirect_to notebooks_addtask_path
     end
   end
  end
    private

    def find_notebook
      @notebooks = Notebook.find_by(id: params[:id])
    end

    #strong parameters
    def notebook_params
      params.require(:notebook).permit(:name)
    end

  end

todolist/app/helpers/notebooks_helper.rb
module NotebooksHelper
end

todolist/app/views/notebooks/_form.html.erb
<% form_name ||= "Manage" %>
<h1 class="text-center">  <%= form_name %> notebook </h1>
<%= form_for @notebooks , method: (form_name.downcase == 'edit' ? 'put' : 'post') do |f| %>
  <% if @notebooks.errors.any? %>
      <div class="error" id="error_explanation">
        <h2>
          <i class="fa fa-times-circle"></i>
          <%= pluralize(@notebooks.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @notebooks.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <div class="form-group">

    <label>Name Notebook</label>
    <%= f.text_field :name, class: "form-control" %>
    <%= f.label :User %>
    <input type="text" class: "form-control" value=<%=current_user.email%> id="cantidad" readonly="readonly"></input>
  </div>
  <%= f.submit "#{form_name} notebook", class: "btn btn-lg boton-color btn-block" %>
  <a href="<%= notebooks_path %>" class="btn btn-lg boton-color-dos btn-block"> View all </a>
<% end %>

todolist/app/views/notebooks/delete.html.erb
<h1>Notebooks#delete</h1>
<p>Find me in app/views/notebooks/delete.html.erb</p>

todolist/app/views/notebooks/edit.html.erb
<div class="container">
  <%= render "form" , form_name: params[:action].capitalize %>
</div>

todolist/app/views/notebooks/index.html.erb
<div class="container">
  <h1 class="text-center"> Notebooks </h1>
  <section class="row text-center cities-controls">
      <a href="<%= new_notebook_path %>" class="btn btn-lg boton-color btn-block"> New Notebook </a>
  </section>
  <% @notebooks.each do |a| %>
    <article class="row city">
      <ul class="view-padding li-view">
        <li class="col-md-2"><strong><%= a.name %></strong></li>
        <li class="col-md-1"><a href="<%= notebook_path(a.id) %>" data-method="delete" class="btn btn-danger"> Delete </a></li>
        <li class="col-md-1"><a href="<%= edit_notebook_path(a.id) %>" class="btn btn-primary"> Edit </a></li>
      </ul>
    </article>
  <% end if @notebooks.any? %>
</div>

todolist/app/views/notebooks/new.html.erb
<h1>Notebooks new</h1>
<div class="container">
  <%= render "form" , form_name: params[:action].capitalize %>
</div>