todolist/config/routes.rb
Rails.application.routes.draw do

  get 'notebooks/index'

  get 'notebooks/new'

  get 'notebooks/update'

  get 'notebooks/delete'

  devise_for :users, controllers: {
          sessions: 'users/sessions',
          passwords: 'users/passwords',
          registrations: 'users/registrations'
  }


  resources :notebooks
  resources :tasks
  get 'notebooks/addtask'
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

todolist/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>Bss Bss !</title>
  </head>

  <body>
    <nav class="navbar navbar-inverse nav-frente">
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <a class="navbar-brand" href="<%= root_path %>"><img src="https://s18.postimg.org/c0pw9zr55/homework.png" width="30" height="30" class="d-inline-block align-top" alt="">TodoList<%= current_user ? "| #{current_user.email}" : '' %>
        </a>
        <ul class="nav navbar-nav navbar left">
          <li>
              <a href="<%= tasks_path%>"><span class="glyphicon glyphicon-plus icono_centro" aria-hidden="true"></span></a>
          </li>
          <li>
              <a href="<%= notebooks_path%>"><span class="glyphicon glyphicon-list-alt icono_centro" aria-hidden="true"></span></a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <% if !current_user %>
              <li><a href="<%= new_user_session_path %>">Log in</a></li>

            <% else %>
              <li><a href="<%= destroy_user_session_path %>" data-method="delete">Log out</a></li>
            <% end %>
        </ul>
       </div>
    </nav>
    <% if flash[:success] or flash[:error] or flash[:notice]%>
    <span class="success flash-message <%= flash[:success] ? 'success' : flash[:error] ? 'error' : flash[:notice] ? 'notice' : '' %>"><i class="fa fa-check"></i>

      <%= flash[:success] ? flash[:success] : flash[:error] ? flash[:error] : flash[:notice] ? flash[:notice] : '' %>
    </span>
    <% end %>
    <%= yield %>
  </body>
</html>